PROJECT = key-value

PROJECT = quadr
SRC_FILES = key-value.c key-value.h main.c Makefile process-file.c process-file.h README

CFLAGS = -g -Wall -std=c11
LDFLAGS = -lm 


$(PROJECT):	key-value.o process-file.o main.o
		$(CC) key-value.o process-file.o main.o -o $@

dist:		$(PROJECT).tar.gz

$(PROJECT).tar.gz: $(SRC_FILES)
		tar -cf $(PROJECT).tar $(SRC_FILES)
		gzip -f $(PROJECT).tar

depend:		
		$(CC) -MM $(CPPFLAGS) *.c

clean:
		rm -f *.o $(PROJECT) $(PROJECT).tar.gz

key-value.o: key-value.c key-value.h
main.o: main.c process-file.h
process-file.o: process-file.c key-value.h process-file.h